steps:
# Step 1: Use ubuntu image to install git and zip, then clone and zip app
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt update
    apt install -y git zip
    git clone https://github.com/<your-username>/<repo-name>.git app
    cd app
    zip -r python-app.zip .

# Step 2: Upload zipped file to GCS bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - app/python-app.zip
  - gs://hello-buck-gugu/python-app.zip
options:
  logging: CLOUD_LOGGING_ONLY
